### ISSUE TITLE
TypeError: DataFrame.set_axis() got an unexpected keyword argument 'inplace'

### ISSUE THREAD

**Issue by XYWjuly2025** [rmarkello/abagen#239]
hi, when i run the code   expression = abagen.get_expression_data(atlas['image'])  

it reports: TypeError: DataFrame.set_axis() got an unexpected keyword argument 'inplace'

How can I solve it? Thank you!

**Comment by JohannesWiesner** [comment]
Can confirm this. Here's the affected line of code:

https://github.com/rmarkello/abagen/blob/dc4a007e4e902e51f97251390c8d1bbf7e58c6d3/abagen/probes_.py#L757

With latest pandas versions, the `inplace` argument does not exist anymore:

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_axis.html

I have these versions_

Python 3.12.8
Pandas 2.2.3
abagen 0.1.3

**Comment by JohannesWiesner** [comment]
Ah, I see, related to:

https://github.com/rmarkello/abagen/issues/232

Will updated to 0.1.4

**Comment by JohannesWiesner** [comment]
Updating to 0.1.4 solved it for me

**Comment by dyjung130** [comment]
Still not working even after updating to 0.1.4...

**Comment by JohannesWiesner** [comment]
> Still not working even after updating to 0.1.4...

Did you directly install from the repo?

**Comment by dyjung130** [comment]
Ah nevermind. I restarted IDE and it is working now 💯 . Thanks!

**Comment by Lyy-River** [comment]
> Ah, I see, related to:
> 
> [#232](https://github.com/rmarkello/abagen/issues/232)
> 
> Will updated to 0.1.4

I would like to know how to get 0.1.4 , I upgrade abagen but the latest version is 0.1.3

**Comment by Lyy-River** [comment]
I noticed it when I use abagen , you can watch my tutorial.
https://lyy-river.github.io/posts/2025-10-22-abagen_start/

**Comment by liuzhenqi77** [comment]
This should have already been fixed in the main branch. There's no need to apply custom code changes.
